package com.how2java.springboot.dao;
 
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import com.how2java.springboot.pojo.userbill;
import com.how2java.springboot.pojo.userbillExample;

@Mapper
public interface userbillMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userbill
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    long countByExample(userbillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userbill
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    int deleteByExample(userbillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userbill
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    int deleteByPrimaryKey(String loginid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userbill
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    int insert(userbill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userbill
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    int insertSelective(userbill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userbill
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    List<userbill> selectByExample(userbillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userbill
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    userbill selectByPrimaryKey(String loginid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userbill
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    int updateByExampleSelective(@Param("record") userbill record, @Param("example") userbillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userbill
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    int updateByExample(@Param("record") userbill record, @Param("example") userbillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userbill
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    int updatetx(userbill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userbill
     *
     * @mbg.generated Fri Mar 13 11:23:59 CST 2020
     */
    int updateByPrimaryKey(userbill record);
    /**
     * 登录
     *
     */
    public userbill login(userbill userbill);
}